/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef cvrpc_CONSTANTS_H
#define cvrpc_CONSTANTS_H

#include "cvrpc_types.h"

namespace cvrpc {

class cvrpcConstants {
 public:
  cvrpcConstants();

};

extern const cvrpcConstants g_cvrpc_constants;

} // namespace

#endif
