/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "cvrpc_constants.h"

namespace cvrpc {

const cvrpcConstants g_cvrpc_constants;

cvrpcConstants::cvrpcConstants() {
}

} // namespace

